# Generated by Django 3.2 on 2021-12-21 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portofillo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='description',
        ),
        migrations.RemoveField(
            model_name='about',
            name='image',
        ),
        migrations.RemoveField(
            model_name='about',
            name='title',
        ),
        migrations.AddField(
            model_name='about',
            name='descriptionL',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='descriptionR',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='imageL',
            field=models.ImageField(blank=True, null=True, upload_to='portofillo'),
        ),
        migrations.AddField(
            model_name='about',
            name='imageR',
            field=models.ImageField(blank=True, null=True, upload_to='portofillo'),
        ),
        migrations.AddField(
            model_name='about',
            name='titleL',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='titleR',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='goodat',
            name='description',
            field=models.TextField(max_length=130),
        ),
        migrations.AlterField(
            model_name='goodat',
            name='title',
            field=models.CharField(max_length=15),
        ),
    ]
