# Generated by Django 3.2 on 2021-12-21 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portofillo', '0002_auto_20211221_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodat',
            name='subtitle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='goodat',
            name='description',
            field=models.TextField(blank=True, max_length=130, null=True),
        ),
        migrations.AlterField(
            model_name='goodat',
            name='title',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
